### ISSUE TITLE
データ通信中のローディングについて

### ISSUE THREAD

**Issue by mizushima1226** [yiinuma/React-MemoApp_TypeScript#1]
チェックアイコンで更新したりなどすると、ローディングのUIが表示され、ボタンクリックなどの操作が効かないように制御しているかと思います

タスクの件数が多い場合、ローディング中にスクロールすると、ボタンをクリックできる領域がありました
また、inputを入力を受け付ける状態で、エンターキ押下で登録できるようになっているようです

どこまで制御するか？があると思いますが、
inputやボタンクリックを無効化するのではれば、明示できに`disabled`のpropsを指定するのが確実です💡

**Comment by yiinuma** [comment]
list表示の各buttonにdisable={Loading}  でボタン無効にできるので修正します
submitはreturnで受け付けないようにするの対応します

**Comment by mizushima1226** [comment]
こちらは未対応でしょうか？👀

**Comment by yiinuma** [comment]
対お済みです
> タスクの件数が多い場合、ローディング中にスクロールすると、ボタンをクリックできる領域がありました

ActionButtonにlodaing中に非活性になるようにdisableを追加しています
  ` <button disabled={loading}>`

> また、inputを入力を受け付ける状態で、エンターキ押下で登録できるようになっているようです

inputからbuttonタグに変更しエンターキー押下で登録できないようにしました
またtitleが空の時にdisableで非活性にしました

 `<input id="submit" type="submit" />
`　⇨ `
<button  id="submit"  type="button"  disabled={title === ''} >`

**Comment by mizushima1226** [comment]
おっと、ローディングはグローバルステートでしたね。。。
修正確認できました！

**Comment by mizushima1226** [comment]
ローディングをグローバルステートで管理するのは色々問題が出てくるので別でissueあげますね！
