### ISSUE TITLE
グローバルステート管理について

### ISSUE THREAD

**Issue by mizushima1226** [yiinuma/React-MemoApp_TypeScript#6]
recoilとContextを併用しているようですが、これは練習の意味も含めて併用している、の認識でOKでしょうか？👀
意図せず併用してしまっている場合、どちらか一方に統一するのが良さそうです〜
意図的なものなら問題ないと思います👍→その場合このissueはCloseしてもらってOKです〜

**Comment by yiinuma** [comment]
contextを削除しrecoilに統一

**Comment by mizushima1226** [comment]
👍
