### ISSUE TITLE
未使用のコンポーネントについて

### ISSUE THREAD

**Issue by mizushima1226** [yiinuma/React-MemoApp_TypeScript#7]
ざっと見た感じ、未使用のコンポーネントいくつか見受けられました〜
レビュー時や後から自分自身で見返すとき、混乱の元となる可能性あるので削除してしまった方が良いかもです〜

- ClearList
- GetWebApi
- Header

**Comment by yiinuma** [comment]
上記リストを含めて不要なコンポーネントを削除しました

**Comment by mizushima1226** [comment]
👍
